### ISSUE TITLE
issue with materials getId() is deprecated

### ISSUE THREAD

**Issue by heathfx** [Maxlego08/TemplatePlugin#3]
When I compile the template without any modifications using a 1.15.2 buildtools spigot.jar to satisfy the local dependencies, I get this error when running on tuinity (a fork of papermc that adds unticked view distance, i have not tried spigot). The getId() method of materials is deprecated, but I see you using it in the problem code. I think you have to use the name() method and reference the materials by their names (String) instead of by ID (int).

How are you able to make this work on 1.15.2? The only way I can make it work is to completely rip out inventory manager, which sucks, because I want to use that feature in the plugin I'm writing.

If you are going to advertise support for 1.15.2, then this really needs to be fixed.

```
[03:22:32 INFO]: [TemplatePlugin] Enabling TemplatePlugin v0.0.2.2
[03:22:32 INFO]: [TemplatePlugin v0.0.2.2] === ENABLE START ===
[03:22:32 INFO]: [TemplatePlugin v0.0.2.2] Plugin Version V0.0.2.2
[03:22:32 ERROR]: Error occurred while enabling TemplatePlugin v0.0.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at fr.maxlego08.template.Template.onEnable(Template.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at org.bukkit.Material.getId(Material.java:3334) ~[patched_1.15.2.jar:git-Tuinity-"e0cce97"]
        at fr.maxlego08.template.zcore.utils.ZUtils.<clinit>(ZUtils.java:244) ~[?:?]
        ... 10 more
[03:22:32 INFO]: [TemplatePlugin] Disabling TemplatePlugin v0.0.2.2
[03:22:32 INFO]: [TemplatePlugin v0.0.2.2] === DISABLE START ===
[03:22:32 INFO]: [TemplatePlugin v0.0.2.2] === DISABLE DONE (0ms) ===

```

**Comment by Maxlego08** [comment]
Hello,

It works very well with spigot, I developed the plugin with spigot and not a fork, I think that is the problem, just delete the code in the ZUtils class to correct the error

**Comment by heathfx** [comment]
I re-tried building from scratch and set up my pom.xml a little bit different and got it to work on the exact same server jar.

I cannot build this out of the box, I had to make several modifications to the pom.xml (ignore the craftbukkit version, that is just my local copy of spigot 1.15.2), you really should add some documentation to get successful build when starting with nothing. I think you are assuming a lot of things about someone's existing build environment. A better "getting started guide" that includes how to set up the dependencies would be a big help.

I also had to move the plugin.yml into src and add a resource definition to make plugin.yml get included in the built jar.
```

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>PluginTemplate</groupId>
    <artifactId>PluginTemplate</artifactId>
    <version>0.0.01</version>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src</directory>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <!-- This adds the Spigot Maven repository to the build -->
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>
    <dependencies>
        <!--This adds the Spigot API artifact to the build -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.15.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.org.apache</groupId>
            <artifactId>jaxp-ri</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>craftbukkit</groupId>
            <artifactId>org.bukkit.craftbukkit</artifactId>
            <version>1</version>
        </dependency>
    </dependencies>   
</project>
```

**Comment by heathfx** [comment]
I traced it to the exact cause. adding api-version: 1.15 to the plugin.yml is what's killing it.

Isn't that good programming practice to specify an API version? The fact that this flat-out will not work with any supported api-version seems a little sloppy for something meant to be a template and "gold standard" for starting a new plugin.

**Comment by Maxlego08** [comment]
I use the template for all plugins and I never put the version API, because my plugins are compatible from 1.7.10 to 1.15.2 maybe your problem is due to this
